apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amadeus-data
  namespace: amadeus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
