apiVersion: v1
kind: Service
metadata:
  name: amadeus-node
  namespace: amadeus
  labels:
    app: amadeus-node
spec:
  type: LoadBalancer
  selector:
    app: amadeus-node
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: p2p
    port: 36969
    targetPort: p2p
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: amadeus-node-headless
  namespace: amadeus
  labels:
    app: amadeus-node
spec:
  clusterIP: None
  selector:
    app: amadeus-node
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: p2p
    port: 36969
    targetPort: p2p
    protocol: UDP
